<a href="https://colab.research.google.com/github/soku1203/Artificial-Intelligence/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [28]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [29]:
tf.__version__

'2.8.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [30]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [31]:
print(X,'\n')
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]] 

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [33]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [34]:
ann.add(tf.keras.layers.Dense(units = 6 ,activation = 'relu'))

### Adding the second hidden layer

In [35]:
ann.add(tf.keras.layers.Dense(units = 6 ,activation = 'relu'))

### Adding the output layer

In [36]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [37]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [38]:
ann.fit(X_train , y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 47981.6680
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 155.2766
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 145.2449
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 139.8510
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 133.5107
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 126.4242
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 118.8283
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 110.8405
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 102.8041
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 94.7824
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 86.8165
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - loss

### Predicting the results of the Test set

In [39]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)), 1))

[[431.09 431.23]
 [462.2  460.01]
 [465.71 461.14]
 ...
 [472.96 473.26]
 [439.7  438.  ]
 [458.95 463.28]]
